### PR TITLE
UPD copier config

### PR DESCRIPTION
**Pull request by bealdav**

### CODE REVIEW

**Comment by bealdav** [comment]
Hi @simahawk could you help me here ?

Though I'm defined as PSC here, it doesn't work for me.
https://github.com/orgs/OCA/teams/vertical-agriculture-maintainers/members

Maybe I missed something ?

Thanks

cc @sbidoul

**Comment by sbidoul** [comment]
@bealdav the team was not authorized for this project. Should be ok now, please retry.

**Pull request merged**
